CREATE DATABASE BDNOVO;


CREATE TABLE PESSOA (
	COD_PESSOA INT PRIMARY KEY,
	NOME_PESSOA VARCHAR(60)
);

SELECT * FROM PESSOA;

INSERT INTO PESSOA (COD_PESSOA, NOME_PESSOA ) VALUES (1, 'MARIA');
INSERT INTO PESSOA (COD_PESSOA, NOME_PESSOA ) VALUES (2, 'JOÃO');
INSERT INTO PESSOA (COD_PESSOA, NOME_PESSOA ) VALUES (3, 'PAULO');
INSERT INTO PESSOA (COD_PESSOA, NOME_PESSOA ) VALUES (4, 'ANDRE');
INSERT INTO PESSOA (COD_PESSOA, NOME_PESSOA ) VALUES (5, 'PATRICIA');

SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA <> 2;

SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA > 2 AND COD_PESSOA < 4;


-- BETWEEN 

SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA >=2 AND COD_PESSOA <=4;

SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA  BETWEEN  2 AND 4;
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA NOT BETWEEN  2 AND 4;

-- IN/NOT IN 
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA IN (2, 4, 10);
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA NOT IN (2, 4, 10);

SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE COD_PESSOA = 2 OR COD_PESSOA =  4 OR COD_PESSOA = 10;

-- LIKE/NOT LIKE 
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE NOME_PESSOA LIKE 'A%';
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE NOME_PESSOA LIKE '%A';
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE NOME_PESSOA LIKE '%A%';
SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE NOME_PESSOA LIKE 'M_R%';

SELECT COD_PESSOA, NOME_PESSOA FROM PESSOA WHERE NOME_PESSOA NOT LIKE '%A%';

-- FUNÇAÕ DE AGREGAÇÃO 

-- COUNT = TOTAL DE REGISTROS 
-- AVG = (AVERAGE) MÉDIA 
-- SUM = SOMA 
-- MIN = MENOR VALOR 
-- MAX = MAIOR VALOR 

SELECT COUNT(COD_PESSOA) AS TOTAL_PESSOA FROM PESSOA;
SELECT SUM(COD_PESSOA)   AS SOMA_PESSOA  FROM  PESSOA;
SELECT AVG(COD_PESSOA)   AS MEDIA_PESSOA FROM PESSOA; 
SELECT MIN(COD_PESSOA)   AS MENOR_PESSOA FROM PESSOA;
SELECT MAX(COD_PESSOA)   AS MAIOR_PESSOA FROM PESSOA;


